services:
  web:
    image: bitnami/laravel
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=xamavan
      - DB_DATABASE=xamavan
    depends_on:
      - db
  db:
    image: bitnami/mariadb
    volumes:
      - ./db-data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=xamavan
      - MARIADB_DATABASE=xamavan
